<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Snet.Mqtt" Version="26.220.1" />
		<PackageReference Include="Snet.Opc" Version="26.220.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="NuGet.Versioning" Version="7.6.0" />
		<PackageReference Include="sqlite-net-pcl" Version="1.11.285" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Language.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Language.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Language.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Language.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
</Project>
